onload = function() {
    main();
}

const dictionaly = [
[
["地殻", "crust"],
["外核", "outer core"],
["内核", "inner core"],
["大陸地殻", "continental crust"],
["海洋地殻", "oceanic crust"],
["プレート境界", "boundary"],
["プレート境界", "plate margin"],
["狭まる境界", "destructive margin"],
["広がる境界", "constructive margin"],
["ずれる境界", "conservative margin"],
["海溝", "ocean trench"],
["半球", "hemisphere"],
["赤道", "equator"],
["更新世の", "Pleistocene"],
["氷河期", "glacial period"],
["北回帰線", "Tropic of Cancer"],
["南回帰線", "Tropic of Capricorn"],
["成層圏", "stratosphere"],
["地軸", "the earth’s axis"],
["赤道収束帯", "inter-tropical convergence zone"],
["亜熱帯高圧帯", "subtropical zone of high pressure"],
["コリオリの力", "Coriolis force"],
["大圏航路", "orthodrome"],
["春分・秋分", "equinox"],
["海水面変動の", "eustatic"],
["アセノスフェア", "asthenosphere"],
["リソスフェア", "lithosphere"],
["狭まる境界", "convergent boundary"],
["広がる境界", "divergent boundary"],
["(プレートが) 沈み込む", "subduct"],
["スラブ", "slab"],
["ファンデフカプレート", "Juan de Fuca plate"],
["ココスプレート", "Cocos plate"],
["南極プレート", "Antarctic plate"],
["インドプレート", "Indian plate"],
["オーストラリアプレート", "Australian plate"],
["南アメリカプレート", "South American plate"],
["ユーラシアプレート", "Eurasian plate"],
["ナスカプレート", "Nazca plate"],
["カリブプレート", "Caribbean plate"],
["北アメリカプレート", "North American Plate"],
["太平洋プレート", "Pacific plate"],
["フィリピン海プレート", "Philippines plate"],
["オーロラ", "aurora"],
["流星群", "meteor shower"],
["(プレートの) 沈み込み", "subduction"],
["大気の", "aerial"],
["子午線", "meridian "],
["経度", "longitude"],
["緯度", "latitude"],
["自転", "Earth’s rotation"],
["対流圏", "troposphere"],
["中間圏", "mesosphere"],
["熱圏", "thermosphere"],
["慣性", "inertia"],
["大圏航路", "great circle"],
["地形", "topography"],
["アイソスタシーの変化", "isostatic change"],
["赤外線", "infrared ray"],
["紫外線", "ultraviolet ray"],
["中央海嶺", "mid-ocean ridge"],
["和達―ベニオフ帯", "Wadachi-Benioff Zone"],
["南極大陸", "Antarctica"],
["ハドレー循環", "Hadrey cell"],
["フェレル循環", "Ferrel cell"],
["極循環", "Polar cell"],
["楕円", "ellipse"],
],
[
["堆積岩", "sedimentary rock"],
["氷河", "glacier"],
["楯状火山", "shield volcano"],
["ドーム状火山", "dome volcano"],
["火山灰", "ash"],
["二酸化硫黄", "sulphur dioxide"],
["火砕流", "pyroclastic flow"],
["窒息死させる", "suffocate"],
["泥流", "mudflow"],
["泥流", "lahar"],
["マグマだまり", "magma basin"],
["カルデラ", "caldera"],
["火成岩", "igneous rock"],
["変成岩", "metamorphic rock"],
["深成岩", "intrusive rock"],
["火山岩", "extrusive rock"],
["斑状組織", "coarse texture"],
["岩脈", "dyke"],
["岩床", "sill"],
["流紋岩", "rhyolite"],
["安山岩", "andesite"],
["玄武岩", "basalt"],
["花崗岩", "granite"],
["閃緑岩", "diorite"],
["斑糲岩 ", "gabbro"],
["石炭紀", "carboniferous"],
["チョーク(鉱物) ", "chalk"],
["堆積する", "deposit"],
["浸食する", "erode"],
["凝縮する(続成作用) ", "compact"],
["大理石", "marble"],
["頁岩", "shale"],
["風化", "weather"],
["浸食", "erosion"],
["海底", "sea bed"],
["石化作用", "lithification"],
["第四紀", "quaternary"],
["第三紀", "tertiary"],
["岩石のサイクル", "rock cycle"],
["物理的風化", "mechanical weathering"],
["化学的風化", "chemical weathering"],
["生物的風化", "biological weathering "],
["剥離作用", "exfoliation"],
["はがれる", "peel off"],
["溶ける", "dissolve"],
["可溶性の", "soluble"],
["炭酸カルシウム", "calcium carbonate"],
["岩山", "tor"],
["荒地", "moorland"],
["酸性の", "acidic"],
["傾く", "tilt"],
["崖・急斜面", "escarpment"],
["帯水層", "aquifer"],
["浸透性の", "permeable"],
["蓄える", "store"],
["不浸透性の", "impermeable"],
["湧水帯", "spring line"],
["かれ谷", "dry valley"],
["浸食する", "eat away"],
["舗装", "pavement"],
["ドリーネ", "swallow hole"],
["洞窟", "cavern"],
["峡谷", "gorge"],
["凝結する", "solidify"],
["鍾乳石", "stalactite"],
["石筍", "stalagmite"],
["塩分", "salinity"],
["循環 ", "circulation"],
["地下水", "groundwater"],
["水循環", "hydrological cycle"],
["蒸発散", "evapotranspiration"],
["染み込み", "infiltration"],
["浸透", "percolation"],
["側方浸透流 (地下水面より上を流れる地下水)", "through flow"],
["流域", "drainage basin"],
["分水嶺", "watershed"],
["支流", "tributary"],
["水源", "source"],
["合流", "confluence"],
["河口", "mouth"],
["流路", "course"],
["上流", "upper course"],
["中流", "middle course"],
["下流", "lower course"],
["傾斜", "gradient"],
["断面図", "profile"],
["運搬作用", "transportation"],
["水圧", "hydraulic"],
["破片", "fragment"],
["丸くする", "round off"],
["滝", "waterfall"],
["滝つぼ", "plunge pool"],
["尾根", "spur"],
["組み合わさる", "interlock"],
["蛇行", "meander"],
["三日月湖", "ox-bow lake"],
["氾濫原", "flood plain"],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],
["", ""],],
[

],
[

],
[

],
[

],
[

],
[

],
[

],
[

],
];
